/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddPlan: typeof import('./src/components/AddPlan.vue')['default']
    CalendarMini: typeof import('./src/components/CalendarMini.vue')['default']
    CalendarOneWeek: typeof import('./src/components/CalendarOneWeek.vue')['default']
    CalendarSearch: typeof import('./src/components/CalendarSearch.vue')['default']
    CalendarWeather: typeof import('./src/components/CalendarWeather.vue')['default']
    DiaryList: typeof import('./src/components/DiaryList.vue')['default']
    DiaryMini: typeof import('./src/components/DiaryMini.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    InsList: typeof import('./src/components/InsList.vue')['default']
    InsMini: typeof import('./src/components/InsMini.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    NewBtn: typeof import('./src/components/NewBtn.vue')['default']
    PlanList: typeof import('./src/components/PlanList.vue')['default']
    RegisterForm: typeof import('./src/components/RegisterForm.vue')['default']
    UserInfoManager: typeof import('./src/components/dialog/UserInfoManager.vue')['default']
    UserTagManager: typeof import('./src/components/dialog/UserTagManager.vue')['default']
  }
}
